#!/usr/bin/env Rscript
# """
# @description
# This script tests perturbation effects on endothelial-state UCell scores with
# SCEPTRE using all singlet cells from the filtered Perturb-seq dataset. It
# loads a guide-by-cell matrix, cell metadata, precomputed technical covariates,
# and the endothelial-state score matrix, then runs high-MOI mixture assignment,
# calibration, and discovery analysis.
#
# Key features:
# - Uses endothelial-state UCell scores as the SCEPTRE response matrix.
# - Restricts analysis to singlet cells shared across the metadata, guide, and
#   score matrices.
# - Applies mixture-model guide assignment with batch and cell type
#   covariates before discovery testing.
#
# @dependencies
# - sceptre: perturbation effect testing framework.
# - Matrix: sparse matrix handling.
# - dplyr: metadata wrangling.
#
# @examples
# - Source this script in RStudio and update the user-editable input block.
# - Run section by section to inspect the harmonized inputs before starting SCEPTRE.
# """

suppressPackageStartupMessages({
  library(Matrix)
  library(dplyr)
  library(sceptre)
})

## -------------------------------------------------------------------------
## User-editable inputs and output names
## -------------------------------------------------------------------------
project_root <- "."

# Guide-to-target annotation table with one row per guide and two columns:
# `grna_id` and `grna_target`.
guide_target_table_csv <- file.path(project_root, "data", "perturbseq_guide_target_table.csv")

# RData file that loads `gRNA_data` and `meta_data` for the filtered screen.
sceptre_input_rdata <- file.path(project_root, "data", "filtered_perturbseq_sceptre_input_objects.RData")

# RData file that loads `covariate_data` for the singlet-cell analysis.
singlet_covariates_rdata <- file.path(project_root, "data", "filtered_perturbseq_singlet_covariates.RData")

# Signatures-by-cells endothelial-state score matrix generated by the scoring script.
endothelial_state_score_matrix_rds <- file.path(project_root, "output", "endothelial_state_scoring", "endothelial_state_ucell_scores_matrix.rds")

output_dir <- file.path(project_root, "output", "endothelial_state_sceptre")
run_label <- "all_singlet_endothelial_state_scores"
n_threads <- 4L
assignment_parallel <- FALSE

if (!dir.exists(output_dir)) {
  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
}

required_files <- c(
  guide_target_table_csv,
  sceptre_input_rdata,
  singlet_covariates_rdata,
  endothelial_state_score_matrix_rds
)

missing_files <- required_files[!file.exists(required_files)]
if (length(missing_files) > 0L) {
  stop(
    "The following input files were not found:\n",
    paste(" -", missing_files, collapse = "\n"),
    "\nUpdate the user-editable input block before running the script.",
    call. = FALSE
  )
}

result_dir <- file.path(output_dir, run_label)
if (!dir.exists(result_dir)) {
  dir.create(result_dir, recursive = TRUE, showWarnings = FALSE)
}

cat("Session info at script start:\n")
print(sessionInfo())

## -------------------------------------------------------------------------
## Load the guide table, screen inputs, and endothelial-state score matrix
## This block brings together the three inputs needed for SCEPTRE.
## -------------------------------------------------------------------------
message("Reading guide-to-target annotation table: ", guide_target_table_csv)
guide_target_table <- read.csv(guide_target_table_csv, stringsAsFactors = FALSE)

if (!all(c("grna_id", "grna_target") %in% colnames(guide_target_table))) {
  if (ncol(guide_target_table) == 2L) {
    colnames(guide_target_table) <- c("grna_id", "grna_target")
  } else {
    stop(
      "Guide-to-target table must contain `grna_id` and `grna_target` columns.",
      call. = FALSE
    )
  }
}

message("Loading filtered screen inputs: ", sceptre_input_rdata)
load(sceptre_input_rdata)
message("Loading singlet covariates: ", singlet_covariates_rdata)
load(singlet_covariates_rdata)

if (!exists("gRNA_data") || !exists("meta_data")) {
  stop("`sceptre_input_rdata` must load objects named `gRNA_data` and `meta_data`.", call. = FALSE)
}
if (!exists("covariate_data")) {
  stop("`singlet_covariates_rdata` must load an object named `covariate_data`.", call. = FALSE)
}

message("Reading endothelial-state score matrix: ", endothelial_state_score_matrix_rds)
response_matrix <- readRDS(endothelial_state_score_matrix_rds)
if (!inherits(response_matrix, "dgCMatrix")) {
  response_matrix <- as(response_matrix, "dgCMatrix")
}

## -------------------------------------------------------------------------
## Restrict the analysis to singlet cells shared across all inputs
## This block harmonizes barcodes and defines the covariates used downstream.
## -------------------------------------------------------------------------
filtered_metadata <- meta_data %>%
  filter(doublet == "singlet") %>%
  mutate(across(c(cell.type.l1, cell.type.l2, batch), as.factor))

if (nrow(filtered_metadata) == 0L) {
  stop("No singlet cells remained after filtering `meta_data`.", call. = FALSE)
}
if (!("cell.type.l1" %in% colnames(filtered_metadata))) {
  stop("Metadata is missing required column `cell.type.l1`.", call. = FALSE)
}
if (!("p_mito" %in% colnames(filtered_metadata))) {
  stop("Metadata is missing required column `p_mito`.", call. = FALSE)
}

shared_barcodes <- Reduce(
  intersect,
  list(
    rownames(filtered_metadata),
    rownames(covariate_data),
    colnames(gRNA_data),
    colnames(response_matrix)
  )
)

if (length(shared_barcodes) == 0L) {
  stop("No shared barcodes were found across metadata, covariates, guide counts, and score matrix.", call. = FALSE)
}

filtered_metadata <- droplevels(filtered_metadata[shared_barcodes, , drop = FALSE])
covariate_data <- covariate_data[shared_barcodes, , drop = FALSE]
gRNA_data <- gRNA_data[, shared_barcodes]
response_matrix <- response_matrix[, shared_barcodes]

extra_covariates <- filtered_metadata %>%
  transmute(
    p_mito = p_mito,
    batch = droplevels(as.factor(batch)),
    cell_type_l1 = droplevels(as.factor(cell.type.l1))
  )

if ("batch" %in% colnames(covariate_data)) {
  covariate_data$batch <- droplevels(as.factor(covariate_data$batch))
}
covariate_data$cell_type_l1 <- droplevels(as.factor(filtered_metadata$cell.type.l1))

message("Shared singlet cells retained for SCEPTRE: ", length(shared_barcodes))
message("Endothelial-state scores in response matrix: ", nrow(response_matrix))

## -------------------------------------------------------------------------
## Configure the SCEPTRE analysis objects
## This block defines the positive controls, discovery pairs, and model terms.
## -------------------------------------------------------------------------
message("Importing the harmonized inputs into SCEPTRE.")
sce <- import_data(
  response_matrix = response_matrix,
  grna_matrix = gRNA_data,
  grna_target_data_frame = guide_target_table,
  extra_covariates = extra_covariates,
  moi = "high"
)

sce@covariate_data_frame <- covariate_data

positive_control_pairs <- construct_positive_control_pairs(sce)
discovery_pairs <- construct_trans_pairs(
  sce,
  positive_control_pairs,
  pairs_to_exclude = "none"
)

assignment_formula <- ~ log(grna_n_nonzero) + log(grna_n_umis) + batch + cell_type_l1
discovery_formula <- ~ log(response_n_nonzero) + log(response_n_umis) +
  log(grna_n_nonzero) + log(grna_n_umis) + batch

message("Setting the positive-control and discovery parameters.")
sce <- sce %>%
  set_analysis_parameters(
    discovery_pairs = discovery_pairs,
    positive_control_pairs = positive_control_pairs,
    formula_object = discovery_formula,
    side = "both"
  )

## -------------------------------------------------------------------------
## Assign guides with the mixture model and run SCEPTRE QC
## This block applies the high-MOI assignment model before discovery testing.
## -------------------------------------------------------------------------
message(
  "Assigning guides with the mixture model (parallel = ",
  assignment_parallel,
  ", n_processors = ",
  n_threads,
  ")."
)
sce <- sce %>%
  assign_grnas(
    method = "mixture",
    formula_object = assignment_formula,
    backup_threshold = 10,
    parallel = assignment_parallel,
    n_processors = n_threads
  )

message("Running SCEPTRE QC.")
sce <- sce %>%
  run_qc()

## -------------------------------------------------------------------------
## Run calibration and discovery analysis on endothelial-state scores
## This block tests perturbation effects on the continuous endothelial-state readouts.
## -------------------------------------------------------------------------
message("Running the calibration check.")
sce <- sce %>%
  run_calibration_check(
    parallel = assignment_parallel,
    n_processors = n_threads,
    output_amount = 2
  )

message("Running the discovery analysis.")
sce <- sce %>%
  run_discovery_analysis(
    parallel = assignment_parallel,
    n_processors = n_threads,
    output_amount = 2
  )

message("Writing SCEPTRE outputs to: ", result_dir)
write_outputs_to_directory(sce, directory = result_dir)

writeLines(capture.output(sessionInfo()), file.path(result_dir, "sessionInfo.txt"))
message("SCEPTRE analysis complete: ", result_dir)
